ManagementFrontAdmin/AdminWeb/Controllers/EnrollmentController.cs
using BLL.DTOs;
using BLL.IServices;
using BLL.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

namespace AdminWeb.Controllers
{
    public class EnrollmentController : Controller
    {
        private readonly IEnrollmentService _enrollmentService;
        private readonly IClassService _classService;
        private readonly IStudentService _studentService;
        private readonly ICourseService _courseService;

        public EnrollmentController(
            IEnrollmentService enrollmentService,
            IClassService classService,
            IStudentService studentService,
            ICourseService courseService)
        {
            _enrollmentService = enrollmentService;
            _classService = classService;
            _studentService = studentService;
            _courseService = courseService;
        }

        public async Task<IActionResult> Index()
        {
            var enrollments = await _enrollmentService.GetAllEnrollments();
            return View(enrollments);
        }

        public async Task<IActionResult> Create()
        {
            await LoadData();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Enrollment obj)
        {
            if (!ModelState.IsValid)
            {
                await LoadData();
                return View(obj);
            }
            string resultMessage = "Lỗi không thể thêm đăng ký lớp này";
            try
            {
                var enrollment = await _enrollmentService.InsertEnrollment(obj);
                if (enrollment != null)
                {
                    TempData["Success"] = "Thêm mới đăng ký lớp thành công";
                    return RedirectToAction("Index");
                }
                await LoadData();
                TempData["Error"] = resultMessage;
                return View(enrollment);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                TempData["Error"] = resultMessage;
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var enrollment = await _enrollmentService.GetEnrollmentById(id);
            if (enrollment == null)
            {
                TempData["Error"] = "Đã xảy ra lỗi khi truy cập đăng ký này";
                return RedirectToAction("Index");
            }
            await LoadData();
            return View(enrollment);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Enrollment obj)
        {
            string resultMessage = "Lỗi không thể sửa đăng ký này";
            if (!ModelState.IsValid)
            {
                await LoadData();
                return View(obj);
            }
            try
            {
                var enrollment = await _enrollmentService.UpdateEnrollment(obj);
                if (enrollment != null)
                {
                    TempData["Success"] = "Chỉnh sửa đăng ký thành công";
                    return RedirectToAction("Index");
                }
                await LoadData();
                TempData["Error"] = resultMessage;
                return View(enrollment);
            }
            catch (Exception ex)
            {
                TempData["Error"] = resultMessage;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var resultMessage = "Xóa đăng ký không thành công";
            try
            {
                var enrollment = await _enrollmentService.DeleteEnrollment(id);
                if (enrollment != null)
                {
                    TempData["Success"] = "Xóa đăng ký thành công";
                    return RedirectToAction("Index");
                }
                TempData["Error"] = resultMessage;
                return View();
            }
            catch (Exception ex)
            {
                TempData["Error"] = resultMessage;
                return View();
            }
        }

        private async Task LoadData()
        {
            ViewBag.Classes = await _classService.GetAllClasses();
            ViewBag.Students = await _studentService.GetAllStudents();
        }

    }
}

ManagementFrontAdmin/AdminWeb/Views/Enrollment/Edit.cshtml
@using BLL.DTOs
@using BLL.DTOs.Enum
@{
    ViewData["Title"] = "Chỉnh sửa đăng ký";
    Layout = "~/Views/Shared/_LayoutProject.cshtml";
}

@model Enrollment

<div>
    <!-- BREADCRUMB -->
    <div class="page-meta">
        <nav class="breadcrumb-style-one" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Đăng ký</a></li>
                <li class="breadcrumb-item" aria-current="page"><a href="@Url.Action("Index", "Enrollment")">Quản lý lớp học</a></li>
                <li class="breadcrumb-item active" aria-current="page">Chỉnh sửa đăng ký</li>
            </ol>
        </nav>
    </div>
    <!-- /BREADCRUMB -->

    <div class="layout-top-spacing col-12">
        <a href="@Url.Action("Index", "Enrollment")" class="btn">
            Trở lại
        </a>
    </div>

    <div class="row layout-top-spacing">
        <div id="user-management" class="col-xxl-8 col-xl-12 layout-spacing">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Chỉnh sửa</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">
                    <div class="col-12">
                        <form asp-action="Edit" method="POST" id="general-settings">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mb-4">
                                        <label>Học viên <strong class="text-danger">*</strong></label>
                                        <select asp-for="StudentId" id="studentId"
                                                class="form-control @(ViewData.ModelState["StudentId"]?.Errors.Count > 0 ? "is-invalid" : "")">
                                            <option value="">-- Chọn học viên --</option>
                                            @foreach (var item in ViewBag.Students)
                                            {
                                                <option value="@item.Id">@item.FullName</option>
                                            }
                                        </select>
                                        <span asp-validation-for="StudentId" class="invalid-feedback"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group mb-4">
                                        <label>Lớp học <strong class="text-danger">*</strong></label>
                                        <select asp-for="ClassId" id="classId"
                                                class="form-control @(ViewData.ModelState["ClassId"]?.Errors.Count > 0 ? "is-invalid" : "")">
                                            <option value="">-- Chọn lớp học --</option>
                                            @foreach (var item in ViewBag.Classes)
                                            {
                                                <option value="@item.Id" data-course-id="@item.CourseId">@item.Name</option>
                                            }
                                        </select>
                                        <span asp-validation-for="ClassId" class="invalid-feedback"></span>
                                    </div>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group mb-4">
                                        <label for="enrllDate">Ngày đăng ký <strong class="text-danger">*</strong></label>
                                        <input asp-for="EnrollDate"
                                               type="date"
                                               id="enrollDate"
                                               class="form-control @(ViewData.ModelState["EnrollDate"]?.Errors.Count > 0 ? "is-invalid" : "")">
                                        <span asp-validation-for="EnrollDate" class="invalid-feedback"></span>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group mb-4">
                                        <label asp-for="Status">
                                            Trạng thái <strong class="text-danger">*</strong>
                                        </label>

                                        <select asp-for="Status"
                                                class="form-control"
                                                asp-items="Html.GetEnumSelectList<EEnrollStatus>()">
                                        </select>

                                        <span asp-validation-for="Status" class="invalid-feedback"></span>
                                    </div>
                                </div>

                            </div>


                            <button type="submit" class="btn btn-primary">Hoàn tất</button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="statbox widget box box-shadow" style="margin-top: 20px">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Thông tin học viên:</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area blog-create-section" id="student-info">
                    <div class="row">
                        <div class="col-xxl-12">
                            <div class="d-flex">
                                <p class="text-start me-1">Mã học viên :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Họ và tên :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Ngày sinh :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Giới tính :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Địa chỉ :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xxl-4 col-xl-12 col-lg-12 col-md-12 col-sm-12 mt-xxl-0 mt-4">
            <div class="statbox widget box box-shadow mt-3">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Thông tin lớp học:</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area blog-create-section" id="class-info">
                    <div class="row">
                        <div class="col-xxl-12">
                            <div class="d-flex">
                                <p class="text-start me-1">Mã lớp học :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Giáo viên :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Tên lớp học :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Ngày bắt đầu :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Ngày kết thúc :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Số lượng học viên :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>

                        </div>
                    </div>
                </div>
            </div>


            <div class="statbox widget box box-shadow mt-3">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Thông tin khóa học:</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area blog-create-section" id="course-info">
                    <div class="row">
                        <div class="col-xxl-12">
                            <div class="d-flex">
                                <p class="text-start me-1">Mã khóa học :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Tên :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Học phí :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>
                            <div class="d-flex">
                                <p class="text-start me-1">Trạng thái :</p>
                                <b>
                                    <p class="text-dark text-bold"></p>
                                </b>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@section FooterFiles {
    <script src="/js/course/course.js"></script>
    <script src="/js/class/class.js"></script>
    <script src="/js/student/student.js"></script>

    <script>
        document.addEventListener("DOMContentLoaded", function(){
            const studentSelect = document.getElementById("studentId");

            function handleInfo(){

                const studentId = studentSelect.value;

                if(studentId){
                    loadStudentInfo(studentId);
                }
            }

            studentSelect.addEventListener("change", handleInfo);

            if(studentSelect.value){
                handleInfo();
            }
        });
        document.addEventListener("DOMContentLoaded", function(){
            const classSelect = document.getElementById("classId");

            function handleInfo(){
                const selectedOption = classSelect.options[classSelect.selectedIndex];

                const classId = classSelect.value;
                const courseId = selectedOption.getAttribute("data-course-id");

                if(classId){
                    loadClassInfo(classId);
                }

                if(courseId){
                    loadCourseInfo(courseId);
                }
            }

            classSelect.addEventListener("change", handleInfo);

            if(classSelect.value){
                handleInfo();
            }
        });
    </script>

}

ManagementFrontAdmin/AdminWeb/Views/Enrollment/Index.cshtml
@using AdminWeb.Helper.Extensions
@using BLL.Response

@{
    ViewData["Title"] = "Enrollment management";
    Layout = "~/Views/Shared/_LayoutProject.cshtml";
}

@model IEnumerable<EnrollmentResponse>

@section Styles {
    <link href="~/plugins/table/datatable/datatables.css" rel="stylesheet" />
    <link href="~/plugins/table/datatable/extensions/col-reorder/col-reorder.datatables.min.css" rel="stylesheet" />
    <link href="~/plugins/table/datatable/extensions/fixed-columns/fixed-columns.datatables.min.css" rel="stylesheet" />
    <link href="~/css/customs/plugins/light/table/datatable/dt-global_style.css" rel="stylesheet" />
    <link href="~/css/customs/plugins/light/table/datatable/custom_dt_custom.css" rel="stylesheet" />


}

<div>
    <!-- BREADCRUMB -->
    <div class="page-meta">
        <nav class="breadcrumb-style-one" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Dịch vụ</a></li>
                <li class="breadcrumb-item active" aria-current="page">
                    Quản lý đăng ký
                </li>
            </ol>
        </nav>
    </div>
    <!-- /BREADCRUMB -->
    <!-- DATATABLE -->
    <div class="row layout-top-spacing">
        <div class="col-xl-12 col-lg-12 col-sm-12">
            <div class="statbox widget box box-shadow">
                <div class="widget-header">
                    <div class="row">
                        <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                            <h4>Quản lý đăng ký</h4>
                        </div>
                    </div>
                </div>
                <div class="widget-content widget-content-area">
                    <div class="layout-top-spacing ps-3 pe-3 col-12 mb-3">
                        <a href="@Url.Action("Create", "Enrollment")" class="btn btn-primary">Thêm mới</a>
                    </div>
                    <table id="enrollment-table" class="table style-3 dt-table-hover" style="width: 100%">
                        <thead>
                            <tr>
                                <th style="width: 5%">STT</th>
                                <th>Mã đăng ký</th>
                                <th>Học viên</th>
                                <th>Lớp học</th>
                                <th>Ngày đăng ký</th>
                                <th>Trạng thái</th>
                                <th class="no-content" style="width: 5%">Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int stt = 1;
                            }
                            @if (Model != null)
                            {

                                @foreach (var enroll in Model)
                                {
                                    <tr>
                                        <td>@stt</td>
                                        <td>@enroll.Id</td>
                                        <td>@enroll.StudentName</td>
                                        <td>@enroll.ClassName</td>
                                        <td>@enroll.EnrollDate</td>
                                        <td>@enroll.Status.GetDisplayName()</td>

                                        <td class="table-controls d-flex justify-content-center align-items-center pt-2">
                                            <li>
                                                <a href="@Url.Action("Edit", "Enrollment", new { id = enroll.Id })"
                                                   class="bs-tooltip edit" data-bs-toggle="tooltip"
                                                   data-bs-placement="top">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                         stroke-width="2" stroke-linecap="round"
                                                         stroke-linejoin="round"
                                                         class="feather feather-edit-2 p-1 br-6 mb-1">
                                                        <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z">
                                                        </path>
                                                    </svg>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#" data-enrollment-id="@enroll.Id"
                                                   class="bs-tooltip delete" data-bs-toggle="tooltip"
                                                   data-bs-placement="top">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                         stroke-width="2" stroke-linecap="round"
                                                         stroke-linejoin="round"
                                                         class="feather feather-trash p-1 br-6 mb-1">
                                                        <polyline points="3 6 5 6 21 6"></polyline>
                                                        <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
                                                    </svg>
                                                </a>
                                            </li>
                                        </td>
                                    </tr>

                                    stt++;
                                }
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- /DATATABLE -->
</div>

<!-- Scripts riêng cho lớp con -->
@section Scripts {
    <script src="~/plugins/table/datatable/datatables.js"></script>
    <script src="~/plugins/table/datatable/extensions/col-reorder/col-reorder.datatables.min.js"></script>
    <script src="~/plugins/table/datatable/extensions/fixed-columns/fixed-columns.datatables.min.js"></script>
    <script>
        $('#enrollment-table').DataTable(
            {
                "dom": "<'dt--top-section'<'row'<'col-12 col-sm-6 d-flex justify-content-sm-start justify-content-center'l><'col-12 col-sm-6 d-flex justify-content-sm-end justify-content-center mt-sm-0 mt-3'f>>>"
                    + "<'table-responsive'tr>"
                    + "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
                "oLanguage": {
                    "oPaginate": {
                        "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>',
                        "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
                    },
                    "sEmptyTable": "Chưa có dữ liệu",
                    "sInfo": "Đang hiển thị trang _PAGE_ của  _PAGES_",
                    "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                    "sSearchPlaceholder": "Tìm kiếm...",
                    "sZeroRecords": "Không có bản ghi nào trùng khớp",
                    "sLengthMenu": "Kết quả :  _MENU_",
                },
                "stripeClasses": [],
                "lengthMenu": [7, 10, 20, 50],
                "pageLength": 10,
                "ordering": false
            });
    </script>

    <script>
        $(document).ready(function () {
            let enrollIdToDelete;

            $('.delete').on('click', function (e) {
                e.preventDefault();
                enrollIdToDelete = $(this).data('enrollment-id');
                $('#deleteModal').modal('show');
            });


            $('#confirmDelete').on('click', function () {
                $.ajax({
                    url: `/Enrollment/Delete`,
                    type: 'POST',
                    data: {
                        id: enrollIdToDelete
                    },
                    success: function (response) {
                        Snackbar.show({
                            text: 'Xóa đăng ký thành công',
                            textColor: '#ddf5f0',
                            backgroundColor: '#00ab55',
                            actionText: 'Bỏ qua',
                            actionTextColor: '#3b3f5c'
                        });

                        setTimeout(function () {
                            location.reload();
                        }, 1000);
                    },
                    error: function (xhr, status, error) {
                        Snackbar.show({
                            text: 'Xóa đăng ký thất bại',
                            textColor: '#fbeced',
                            backgroundColor: '#e7515a',
                            actionText: 'Bỏ qua',
                            actionTextColor: '#3b3f5c'
                        });
                    }
                });

                $('#deleteModal').modal('hide');
            });
        });
    </script>
}